### ISSUE TITLE
Infromation on training/loading pretrained models?

### ISSUE THREAD

**Issue by TSoli** [lorenzopapa5/METER#2]
Hi, thank you for providing your models. I am a bit unsure of exactly what formats the models are saved as in the `models` directory. How can I load them and try them out? I thought maybe there would be a clue in the training code but I could not see it when I skimmed the repo. Thanks!

**Comment by lorenzopapa5** [comment]
# Instantiate the model
model =  build_METER_model(device, arch_type)

# Load the state dictionary into the model
model.load_state_dict(torch.load('FILE.pth'))
